SetActiveLib -work
comp -include "$DSN\src\Afalina_tvk_pkg.vhd" 
comp -include "$DSN\src\ccd285_sync_generator.vhd" 
comp -include "$DSN\src\mpu_res.vhd" 
comp -include "$DSN\Mega\ALTPLL59.vhd" 
comp -include "$DSN\src\afalina_tvk.vhd" 
comp -include "$DSN\src\TestBench\afalina_tvk_TB.vhd" 
asim TESTBENCH_FOR_afalina_tvk 
wave 
wave -noreg CLK_2
wave -noreg CLK_3
wave -noreg CLK_6
wave -noreg CLK_7
wave -noreg XV1A
wave -noreg XV2A
wave -noreg XV3A
wave -noreg XV4A
wave -noreg SG2AA
wave -noreg SG2BA
wave -noreg XSUBA
wave -noreg H1A
wave -noreg H2A
wave -noreg RGA
wave -noreg DATACLKA
wave -noreg SL
wave -noreg SCK
wave -noreg SDATA
wave -noreg ADC_A
wave -noreg SHDA
wave -noreg SHPA
wave -noreg VDA
wave -noreg HDA
wave -noreg PBLKA
wave -noreg CLPDMA
wave -noreg CLPOBA
wave -noreg XV1B
wave -noreg XV2B
wave -noreg XV3B
wave -noreg XV4B
wave -noreg SG2AB
wave -noreg SG2BB
wave -noreg XSUBB
wave -noreg H1B
wave -noreg H2B
wave -noreg RGB
wave -noreg DATACLKB
wave -noreg ADC_B
wave -noreg SHDB
wave -noreg SHPB
wave -noreg VDB
wave -noreg HDB
wave -noreg PBLKB
wave -noreg CLPDMB
wave -noreg CLPOBB
wave -noreg LVDS_D
wave -noreg LVDS_CLK
wave -noreg A
wave -noreg DQ
wave -noreg BA
wave -noreg WE
wave -noreg CAS
wave -noreg RAS
wave -noreg CS
wave -noreg UDQM
wave -noreg LDQM
wave -noreg CKE
wave -noreg CLK_SDRAM
wave -noreg MPU_MODE
wave -noreg MPU_RESET
wave -noreg MPU_A
wave -noreg MPU_D
wave -noreg MPU_RD
wave -noreg MPU_WR
wave -noreg MPU_INT0
wave -noreg MPU_INT1
wave -noreg ALE
wave -noreg PSEN
wave -noreg RESET_842
wave -noreg ADUC_TXD
wave -noreg ADUC_RXD
wave -noreg RS232_TXD
wave -noreg RS232_RXD
wave -noreg RS485_TXD
wave -noreg RS485_RXD
wave -noreg RS485_MODE
wave -noreg RS485_PV
wave -noreg BR
wave -noreg PH
wave -noreg RES1
wave -noreg RES2
wave -noreg KT
# The following lines can be used for timing simulation
# acom <backannotated_vhdl_file_name>
# comp -include "$DSN\src\TestBench\afalina_tvk_TB_tim_cfg.vhd" 
# asim TIMING_FOR_afalina_tvk 
