# File: dsp_af__pin_assignments.tcl
# Generated on: Яђ рту 8 2008 11:39:13

# Load Quartus II Tcl Project package
package require ::quartus::project

set_location_assignment PIN_L7 -to A[0]
set_location_assignment PIN_P6 -to A[1]
set_location_assignment PIN_N6 -to A[10]
set_location_assignment PIN_R8 -to A[11]
set_location_assignment PIN_T8 -to A[12]
set_location_assignment PIN_M7 -to A[2]
set_location_assignment PIN_N8 -to A[3]
set_location_assignment PIN_M9 -to A[4]
set_location_assignment PIN_L9 -to A[5]
set_location_assignment PIN_N9 -to A[6]
set_location_assignment PIN_K9 -to A[7]
set_location_assignment PIN_R7 -to A[8]
set_location_assignment PIN_K8 -to A[9]
set_location_assignment PIN_G16 -to ADC_A[0]
set_location_assignment PIN_H15 -to ADC_A[1]
set_location_assignment PIN_F16 -to ADC_A[10]
set_location_assignment PIN_G15 -to ADC_A[11]
set_location_assignment PIN_J13 -to ADC_A[2]
set_location_assignment PIN_J14 -to ADC_A[3]
set_location_assignment PIN_H16 -to ADC_A[4]
set_location_assignment PIN_J15 -to ADC_A[5]
set_location_assignment PIN_J16 -to ADC_A[6]
set_location_assignment PIN_K15 -to ADC_A[7]
set_location_assignment PIN_D16 -to ADC_A[8]
set_location_assignment PIN_F15 -to ADC_A[9]
set_location_assignment PIN_C16 -to ADC_B[0]
set_location_assignment PIN_D15 -to ADC_B[1]
set_location_assignment PIN_B16 -to ADC_B[10]
set_location_assignment PIN_C15 -to ADC_B[11]
set_location_assignment PIN_F13 -to ADC_B[2]
set_location_assignment PIN_F14 -to ADC_B[3]
set_location_assignment PIN_B13 -to ADC_B[4]
set_location_assignment PIN_A13 -to ADC_B[5]
set_location_assignment PIN_B14 -to ADC_B[6]
set_location_assignment PIN_A15 -to ADC_B[7]
set_location_assignment PIN_C14 -to ADC_B[8]
set_location_assignment PIN_D14 -to ADC_B[9]
set_location_assignment PIN_A2 -to ADUC_RXD
set_location_assignment PIN_B3 -to ADUC_TXD
set_location_assignment PIN_D6 -to ALE
set_location_assignment PIN_P8 -to BA[0]
set_location_assignment PIN_L6 -to BA[1]
set_location_assignment PIN_P9 -to BR
set_location_assignment PIN_M8 -to CAS
set_location_assignment PIN_L8 -to CKE
set_location_assignment PIN_M16 -to CLK_7
set_location_assignment PIN_M2 -to CLK_2
set_location_assignment PIN_M1 -to CLK_3
set_location_assignment PIN_M15 -to CLK_6
set_location_assignment PIN_T4 -to CLK_SDRAM
set_location_assignment PIN_N16 -to CLPDMA
set_location_assignment PIN_D12 -to CLPDMB
set_location_assignment PIN_L12 -to CLPOBA
set_location_assignment PIN_A12 -to CLPOBB
set_location_assignment PIN_M6 -to CS
set_location_assignment PIN_R16 -to DATACLKA
set_location_assignment PIN_K16 -to DATACLKB
set_location_assignment PIN_T3 -to DQ[0]
set_location_assignment PIN_R3 -to DQ[1]
set_location_assignment PIN_R10 -to DQ[10]
set_location_assignment PIN_T11 -to DQ[11]
set_location_assignment PIN_R11 -to DQ[12]
set_location_assignment PIN_T12 -to DQ[13]
set_location_assignment PIN_R12 -to DQ[14]
set_location_assignment PIN_T13 -to DQ[15]
set_location_assignment PIN_R4 -to DQ[2]
set_location_assignment PIN_T5 -to DQ[3]
set_location_assignment PIN_R5 -to DQ[4]
set_location_assignment PIN_T6 -to DQ[5]
set_location_assignment PIN_R6 -to DQ[6]
set_location_assignment PIN_T7 -to DQ[7]
set_location_assignment PIN_R9 -to DQ[8]
set_location_assignment PIN_T10 -to DQ[9]
set_location_assignment PIN_L13 -to H1A
set_location_assignment PIN_B12 -to H1B
set_location_assignment PIN_M12 -to H2A
set_location_assignment PIN_A11 -to H2B
set_location_assignment PIN_R14 -to HDA
set_location_assignment PIN_C11 -to HDB
set_location_assignment PIN_K11 -to KT[1]
set_location_assignment PIN_K10 -to KT[2]
set_location_assignment PIN_F5 -to KT[3]
set_location_assignment PIN_L4 -to LDQM
set_location_assignment PIN_A14 -to LVDS_CLK
set_location_assignment PIN_L3 -to LVDS_D[0]
set_location_assignment PIN_N3 -to LVDS_D[1]
set_location_assignment PIN_J2 -to LVDS_D[10]
set_location_assignment PIN_J6 -to LVDS_D[11]
set_location_assignment PIN_L2 -to LVDS_D[12]
set_location_assignment PIN_L1 -to LVDS_D[13]
set_location_assignment PIN_D5 -to LVDS_D[14]
set_location_assignment PIN_C2 -to LVDS_D[15]
set_location_assignment PIN_F6 -to LVDS_D[16]
set_location_assignment PIN_F3 -to LVDS_D[17]
set_location_assignment PIN_G1 -to LVDS_D[18]
set_location_assignment PIN_F1 -to LVDS_D[19]
set_location_assignment PIN_N2 -to LVDS_D[2]
set_location_assignment PIN_F2 -to LVDS_D[20]
set_location_assignment PIN_D1 -to LVDS_D[21]
set_location_assignment PIN_F7 -to LVDS_D[22]
set_location_assignment PIN_G5 -to LVDS_D[23]
set_location_assignment PIN_K1 -to LVDS_D[24]
set_location_assignment PIN_K2 -to LVDS_D[25]
set_location_assignment PIN_N1 -to LVDS_D[26]
set_location_assignment PIN_T2 -to LVDS_D[27]
set_location_assignment PIN_P1 -to LVDS_D[3]
set_location_assignment PIN_P2 -to LVDS_D[4]
set_location_assignment PIN_P3 -to LVDS_D[5]
set_location_assignment PIN_R1 -to LVDS_D[6]
set_location_assignment PIN_G2 -to LVDS_D[7]
set_location_assignment PIN_K5 -to LVDS_D[8]
set_location_assignment PIN_J1 -to LVDS_D[9]
set_location_assignment PIN_A5 -to MPU_A[0]
set_location_assignment PIN_B6 -to MPU_A[1]
set_location_assignment PIN_A6 -to MPU_A[2]
set_location_assignment PIN_B7 -to MPU_A[3]
set_location_assignment PIN_E6 -to MPU_A[4]
set_location_assignment PIN_E7 -to MPU_A[5]
set_location_assignment PIN_F8 -to MPU_A[6]
set_location_assignment PIN_F9 -to MPU_A[7]
set_location_assignment PIN_E8 -to MPU_D[0]
set_location_assignment PIN_D8 -to MPU_D[1]
set_location_assignment PIN_B8 -to MPU_D[2]
set_location_assignment PIN_A8 -to MPU_D[3]
set_location_assignment PIN_B9 -to MPU_D[4]
set_location_assignment PIN_C8 -to MPU_D[5]
set_location_assignment PIN_A9 -to MPU_D[6]
set_location_assignment PIN_E10 -to MPU_D[7]
set_location_assignment PIN_A3 -to MPU_INT0
set_location_assignment PIN_B4 -to MPU_INT1
set_location_assignment PIN_L11 -to MPU_MODE
set_location_assignment PIN_B5 -to MPU_RD
set_location_assignment PIN_M11 -to MPU_RESET
set_location_assignment PIN_A4 -to MPU_WR
set_location_assignment PIN_T15 -to PBLKA
set_location_assignment PIN_L15 -to PBLKB
set_location_assignment PIN_L10 -to PH
set_location_assignment PIN_A7 -to PSEN
set_location_assignment PIN_K6 -to RAS
set_location_assignment PIN_K12 -to RES1
set_location_assignment PIN_J11 -to RES2
set_location_assignment PIN_B1 -to RESET_842
set_location_assignment PIN_M10 -to RGA
set_location_assignment PIN_B11 -to RGB
set_location_assignment PIN_C6 -to RS232_RXD
set_location_assignment PIN_F10 -to RS232_TXD
set_location_assignment PIN_D4 -to RS485_MODE
set_location_assignment PIN_D3 -to RS485_PV
set_location_assignment PIN_E5 -to RS485_RXD
set_location_assignment PIN_C3 -to RS485_TXD
set_location_assignment PIN_R13 -to SCK
set_location_assignment PIN_L16 -to SDATA
set_location_assignment PIN_P16 -to SG2AA
set_location_assignment PIN_G11 -to SG2AB
set_location_assignment PIN_P15 -to SG2BA
set_location_assignment PIN_J12 -to SG2BB
set_location_assignment PIN_N14 -to SHDA
set_location_assignment PIN_F11 -to SHDB
set_location_assignment PIN_N15 -to SHPA
set_location_assignment PIN_E11 -to SHPB
set_location_assignment PIN_L14 -to SL
set_location_assignment PIN_T9 -to UDQM
set_location_assignment PIN_T14 -to VDA
set_location_assignment PIN_D11 -to VDB
set_location_assignment PIN_N5 -to WE
set_location_assignment PIN_P11 -to XSUBA
set_location_assignment PIN_E9 -to XSUBB
set_location_assignment PIN_N13 -to XV1A
set_location_assignment PIN_A10 -to XV1B
set_location_assignment PIN_P14 -to XV2A
set_location_assignment PIN_B10 -to XV2B
set_location_assignment PIN_N12 -to XV3A
set_location_assignment PIN_D9 -to XV3B
set_location_assignment PIN_N11 -to XV4A
set_location_assignment PIN_C9 -to XV4B

# Commit assignments
export_assignments